### ISSUE TITLE
[feature request] Add environment variables for configuring database and authorization

### ISSUE THREAD

**Issue by jmny** [influxdata/influxdb-docker#14]
with the postgresql image , the user can set a password /  user / dbname to setup a "ready to use" database , is it possible to add this feature to influxdb too ?

https://hub.docker.com/_/postgres/ ("Environnement variables" sub title)

Regards,

**Comment by rossmcdonald** [comment]
@jmny This is not currently implemented, though it should be relatively straightforward to add.

**Comment by allen13** [comment]
As part of an influxdb ansible playbook I wrote an idempotent python module that does this [exact thing](https://github.com/allen13/influxdb-ansible/blob/master/playbook/roles/influxdb/library/influxdb_user). It wouldn't take much to extract the code and make it respond to environment variables instead of ansible arguments.

**Comment by jmny** [comment]
quick note,  tutum influxdb is a litle outdated, but have a similar postgresql "run.sh" , helping to build user and database : https://github.com/tutumcloud/influxdb/blob/master/0.12/run.sh

**Comment by jsternberg** [comment]
If we offered a way to just run an influxql script file and you could do whatever you want inside of it, would that be good or does there need to be specific environment variables for doing this?

**Comment by jmny** [comment]
I will do a init script based on environment variable, inspired by tutum version , but adapted to influxdata docker image. and perhaps a PR if you are interested, at least a gist.

**Comment by jmny** [comment]
so , I'm here : https://gist.github.com/jmny/c19d404781d27cbe352b9f647600e0c9 , and it's do the job for me.

**Comment by jsternberg** [comment]
I'm growing a bit hesitant to include this functionality. That gist requires that the entrypoint script has a lot of extra logic that seems very difficult to maintain. It also means that you have to play with backgrounding a process and waiting for it to finish in the entrypoint script. If you don't wait for it to finish, you're going to orphan a process in the docker container. I also don't know how well it will translate to the alpine version of the images as the entrypoint needs to be compatible with `sh` too. It also starts requiring us to add tests to ensure that this functionality works whenever a change has to be made.

Since the container volume is meant to be persistent anyway, I don't think it's a very large burden to require an administrator to create the initial user themselves through whatever server deployment method they choose (such as ansible, chef, etc). If you don't need a persistent server, it seems to me like you probably don't need authentication either in the majority of cases.

If somebody wants to build on top of the official images to include this functionality for a more specific use case (such as tutumcloud updating their version), they can either base their image on ours or build their own with this functionality. If you make one of these images and it has sufficient popularity to show that this functionality is desired, we can even either merge the functionality or include a link to your version as an unofficial image in the documentation so that people can more easily find what functionality they desire.

I'm going to close this for now. If there's a counterpoint to the points I brought up or a very compelling reason why 90% or more of people using this image need this functionality, I'll reopen and we'll accept PR's for this feature.

Thank you for your interest.
