### ISSUE TITLE
[BUG] Empty Password for Prompt not working (/usr/bin/influx)

### ISSUE THREAD

**Issue by notes-jj** [influxdata/influxdb-docker#16]
Moved this Bug from https://github.com/influxdata/influxdb/issues/6746 , because the bug seams only to appers in docker containers as e-dard mentioned in the other thread.

**Description**

Calling /usr/bin/influx with `-password ''` or `--password ''` will give error `Unable to parse password.` No prompt is appearing. Help of influx states:
```
  -password 'password'
      Password to connect to the server.  Leaving blank will prompt for password (--password '').
```

**Version:**
I'm using Docker Container influxdb:0.13.0-alpine and also tested influxdb:0.13.0.

**Steps to reproduce:**
```
# Create temp Container
docker run -d \
--name test-influx \
-p 8083:8083 -p 8086:8086 \
-e INFLUXDB_HTTP_AUTH_ENABLED="true" \
influxdb:0.13.0-alpine

# Create admin user in InfluxDB
docker exec -ti test-influx \
/usr/bin/influx -execute "CREATE USER admin WITH PASSWORD 'pass' WITH ALL PRIVILEGES; SHOW USERS"

# Start ash Shell in Container
docker exec -ti test-influx /bin/ash

# Run influx in Container
influx -username 'admin' --password ''
```

**Logs:**
```
/ #  influx -username 'admin' --password ''
Unable to parse password.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.13.0
InfluxDB shell version: 0.13.0

```

```
/ #  influx -username 'admin' -password ''
Unable to parse password.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.13.0
InfluxDB shell version: 0.13.0
```

**Comment by jsternberg** [comment]
This seems to apply to the open source version too. For some reason, an empty password on the command line will still prompt for the password. You'll see the same behavior if you run docker like this:

```
$ docker run --rm -it influxdb:alpine influx -password ''
```

It will ask for the password prompt. You also need to, in general, use `-it` when using the influx command line since a TTY is usually required.

**Comment by notes-jj** [comment]
Hello @jsternberg 

I ran `docker exec -ti test-influx /bin/ash` and then `influx -username 'admin' -password ''` inside the container. Even if I run the command your way, there is no password prompt. Not in `influxdb:0.13.0-alpine` nor `influxdb:0.13.0`

o1da confirmed the bug in https://github.com/influxdata/influxdb/issues/6746

**The `influxdb:0.13.0-alpine` Output**
```
root@jjdocker-grafana [ ~ ]# docker run -d \
> --name test-influx \
> -p 8083:8083 -p 8086:8086 \
> -e INFLUXDB_HTTP_AUTH_ENABLED="true" \
> influxdb:0.13.0-alpine
917f2cad64310c637094a9363f91443c141b555baa898069b7cf4923680feb0e

root@jjdocker-grafana [ ~ ]# docker exec -ti test-influx \
> /usr/bin/influx -execute "CREATE USER admin WITH PASSWORD 'pass' WITH ALL PRIVILEGES; SHOW USERS"
user    admin
admin   true

root@jjdocker-grafana [ ~ ]# docker exec -ti test-influx influx -username 'admin' --password ''
Unable to parse password.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.13.0
InfluxDB shell version: 0.13.0
> quit

root@jjdocker-grafana [ ~ ]# docker exec -ti test-influx influx -username 'admin' -password ''
Unable to parse password.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.13.0
InfluxDB shell version: 0.13.0
> quit
```

**Comment by jsternberg** [comment]
Hm, interesting. It seems to only happen when you use `docker exec`. Can you confirm that you don't experience this problem when using `docker run`?

**Comment by jsternberg** [comment]
It looks like this is related to docker/docker#8755. As a workaround, you can use a separate container like this:

```
$ docker run -it --rm --net=container:influxdb influxdb:alpine influx -password ''
```

Replace `container:influxdb` with the name of your container. I don't think there's anything more we can do about this since it's a docker bug related to not allocating a TTY when using `docker exec`.

**Comment by jsternberg** [comment]
I'm going to close this since I don't think there's anything we can do about this. I've submitted docker-library/docs#596 to remove that example and to specifically cite the issue I pointed to above.

Thanks for helping us find this! If there's anything else we can do, please comment on the issue again with what we can do and I'll reopen the issue.
